config/routes.rb
Rails.application.routes.draw do

  root to: 'static_pages#root'

  resources :users

  resource :sessions, only: [:new, :create, :destroy]

  namespace :api, defaults: {format: :json} do
    resources :texts
    resources :annotations
    resources :descriptions
    resources :users
    resources :authors
    get "search", to: "static_pages#search"
    resources :postlets, only: [:create, :destroy, :update, :index, :show]

  end




end

app/controllers/api/static_pages_controller.rb
class Api::StaticPagesController < ApplicationController

  def search
    @search_results = PgSearch.multisearch(params[:query])
    .page(params[:page])
    # fail
    render :search
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  before_action :require_login

  def root
    render :root
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/root.html.erb
<% redirect_to session_new_url unless logged_in? %>

<header id="header"></header>
<nav id="search-bar"></nav>

<main id="main"></main>



<script>

  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-64315962-1', 'auto');
  ga('send', 'pageview');

Cicadas.boreas = "<%= asset_path("boreas.jpg") %>"
Cicadas.grid = "<%= asset_path("grid.png") %>"


$(document).ready(function(){
  Cicadas.initialize({ cUserId: <%= current_user.id %> });
});

</script>