config/routes.rb
Rails.application.routes.draw do

  root to: 'static_pages#root'

  resources :users

  resource :sessions, only: [:new, :create, :destroy]

  namespace :api, defaults: {format: :json} do
    resources :texts
    resources :annotations
    resources :descriptions
    resources :users
    resources :authors
    get "search", to: "static_pages#search"
    resources :postlets, only: [:create, :destroy, :update, :index, :show]

  end




end

app/models/user.rb
class User < ActiveRecord::Base
  include PgSearch
  multisearchable against: [:username, :uploaded_texts]

  validates :username, :email, :password_digest, presence: true
  validates :username, :email, uniqueness: true
  validates :password, length: {minimum: 6, allow_nil: true}

  has_attached_file :avatar, default_url: "david_bowie.jpg",
        styles: {:medium => "300x300>", :thumb => "100x100>"}
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  attr_reader :password

  has_many :sessions, dependent: :destroy

  has_many :uploaded_texts,
  class_name: "Text",
  foreign_key: :user_id,
  primary_key: :id

  has_many :annotations, dependent: :destroy,
  class_name: "Annotation",
  foreign_key: :author_id,
  primary_key: :id

  has_many :descriptions, dependent: :destroy,
  class_name: "Description",
  foreign_key: :author_id,
  primary_key: :id

  has_many :libraries, dependent: :destroy

  has_many :library_texts, through: :libraries, as: :text

  def authored_texts
    texts = self.uploaded_texts.where(author_is_user: true)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest) == password
  end


  def self.validate_credentials_username(creds)
    user = User.find_by(username: creds[:username])
    if user
      return user if user.is_password?(creds[:password])
    end
    nil
  end

  def set_session_token!
    session = Session.new(user_id: self.id)
    token = session.generate_new_session_token!
    token
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController

  before_action :forbid_login, only: [:new, :create]

  wrap_parameters false

  def show
    @user = User.find(params[:id])
    render :show
  end

  def index
    @users = User.all
    render :index
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(user_params)
    render json: @user
  end

  def destroy
  end

  def user_params
    params.require(:user).permit(:username, :email, :about, :avatar, :about)
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :forbid_login, only: [:new, :create]

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def index
    render :index
  end

  def edit
  end

  def destroy
  end

end

app/helpers/api/users_helper.rb
module Api::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
ubi amor ibi oculus est

app/views/users/new.html.erb
<style>

.background-holder {
  position: absolute;
  left: 0;
  top: 0;
  width: 100%;
  height: 100%;
  z-index:0;
}

.sign-in-background {
  width: 100%;
  height: 100%;
  position: absolute;

}


body {
  background: transparent;
}


.entry-form {
  position: absolute;
  top: 125px;
  left: 0px;
  right: 0px;
  margin-left: auto;
  margin-right: auto;
  width: 310px;
  padding: 25px;
  background: #049100;
  color: #ffc31c;
  margin-top: 220px;
  margin: auto;
  z-index: 1;
  border: 2px solid #3B5E2B;
  border-radius: 5px;
  opacity: 0.95;
}

.entry-form li {
  float: left;
  padding-bottom: 5px;
  width: 300px;
}

.entry-form h2 {
  color: #ffc31c;
  /*font-weight: bold;*/
  font-family: "Sirin Stencil", arial;
  font-size: 26px;
  text-shadow: 1px 1px 2px #3B5E2B;
  text-align: center;
  padding-top: 13px;
  padding-bottom: 5px;
  width: 311px;
}



.entry-form input {
  display: block;
  border: 1px solid #000;
  background: #FFF7DF;
  height: 20px;
  width: 275px;
  border-radius: 5px;
  padding: 5px;
  color: #000;
  margin-top: 5px;
}


.form-propre {
  display: block;
  background: #05ab00;
  padding: 10px;
  margin-top: 5px;
  color: white;
  opacity: 1.0!important;
  width: 290px;
  padding-bottom: 3px;

}

.entry-form label {
  font-size: 17px;
  padding-bottom: 5px;
  text-shadow: 2px 2px 2px #009900;

}

.entry-submit {
  margin: 10px 0px;
  padding: 7px;
  /*border: 2px solid #3B5E2B;*/
  display: inline;
  border-radius: 3px;
  background: #047800;
  text-shadow: 1px 1px 1px #047800;
}

.errors {
  text-align: center;
  font-size: 14px;
  color: blue;
}


.header-logo {
  padding: 14px 10px;
  border-radius: 50%;
  border: 4px solid #009900;
  background: #fff;
  color: #3FBC13;
  box-shadow: 0px 0px 1px black;
  font-size: 36px;
  display: block;
  font-weight: bold;
  vertical-align: center;
  float: left;
  margin-left: 126px;

}


</style>
  <main class="entry">

    <div background-holder>
      <img class="sign-in-background" src='<%= asset_path "bruegel_corn.jpg"%>'/>
    </div>


    <%= render "/layouts/entry_header" %>

    <ul class="entry-form group" action="<%=sessions_url%>" method="post">

      <li>
        <h1 class="header-logo">蝉</h1>
      </li>
      <li>
        <h2>SIGN UP</h2>
      </li>
      <li>
        <form class="form-propre" method="post" action="/users">
          <div class="errors">
          <%= render "shared/errors" %>
          </div>

          <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
          <label>
            Username
            <input type=text name="user[username]" value="<%=@user.username%>">
          </label>
          <label>Email
           <input type="text" name="user[email]" value="<%=@user.email%>">
         </label>
            Password
            <input type="password" name="user[password]" value="">
          </label>
          <button class="entry-submit">Sign Up</button>
        </form>
      </li>
    </ul>
  </main>

app/views/users/show.html.erb
<% @user.uploaded_texts.each do |text| %>
  <%= render "/api/texts/show", text: text %>
<br>
<% end %>